services:
  mysql:
    image: mysql:8.4
    container_name: desafio-votacao-mysql
    environment:
      MYSQL_DATABASE: votacao
      MYSQL_USER: votacao
      MYSQL_PASSWORD: votacao
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - votacao_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  votacao_mysql_data:
